<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="UNINITIALIZE" Id="{991ec388-cac6-487d-b8f8-7cafcc904dc6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UNINITIALIZE : BOOL
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

UNINITIALIZE := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="UNINITIALIZE">
      <LineId Id="8" Count="1" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>